// Jobs/Professions Database - Inspired by theresanaiforthat.com
// 150+ Professions with AI tool recommendations

export interface Profession {
  id: string;
  name: string;
  nameEs: string;
  industry: IndustryType;
  description: string;
  descriptionEs: string;
  aiCount: number;
  tasks: string[];
}

export type IndustryType = 
  | "technology"
  | "healthcare"
  | "finance"
  | "education"
  | "marketing"
  | "design"
  | "business"
  | "legal"
  | "creative"
  | "engineering"
  | "sales"
  | "hr"
  | "media"
  | "science"
  | "services";

export const industries: { id: IndustryType; name: string; nameEs: string; icon: string }[] = [
  { id: "technology", name: "Technology", nameEs: "Tecnología", icon: "💻" },
  { id: "healthcare", name: "Healthcare", nameEs: "Salud", icon: "🏥" },
  { id: "finance", name: "Finance", nameEs: "Finanzas", icon: "💰" },
  { id: "education", name: "Education", nameEs: "Educación", icon: "🎓" },
  { id: "marketing", name: "Marketing", nameEs: "Marketing", icon: "📢" },
  { id: "design", name: "Design", nameEs: "Diseño", icon: "🎨" },
  { id: "business", name: "Business", nameEs: "Negocios", icon: "💼" },
  { id: "legal", name: "Legal", nameEs: "Legal", icon: "⚖️" },
  { id: "creative", name: "Creative", nameEs: "Creativo", icon: "🎬" },
  { id: "engineering", name: "Engineering", nameEs: "Ingeniería", icon: "🔧" },
  { id: "sales", name: "Sales", nameEs: "Ventas", icon: "🛒" },
  { id: "hr", name: "Human Resources", nameEs: "Recursos Humanos", icon: "👥" },
  { id: "media", name: "Media", nameEs: "Medios", icon: "📺" },
  { id: "science", name: "Science", nameEs: "Ciencia", icon: "🔬" },
  { id: "services", name: "Services", nameEs: "Servicios", icon: "🛠️" },
];

export const professions: Profession[] = [
  // Technology
  {
    id: "software-developer",
    name: "Software Developer",
    nameEs: "Desarrollador de Software",
    industry: "technology",
    description: "Designs, develops, and maintains software applications and systems.",
    descriptionEs: "Diseña, desarrolla y mantiene aplicaciones y sistemas de software.",
    aiCount: 567,
    tasks: ["coding", "debugging", "testing", "code-review", "documentation"],
  },
  {
    id: "frontend-developer",
    name: "Frontend Developer",
    nameEs: "Desarrollador Frontend",
    industry: "technology",
    description: "Creates user interfaces and user experiences for websites and applications.",
    descriptionEs: "Crea interfaces de usuario y experiencias de usuario para sitios web y aplicaciones.",
    aiCount: 456,
    tasks: ["ui-design", "web-development", "css-generation", "responsive-design"],
  },
  {
    id: "backend-developer",
    name: "Backend Developer",
    nameEs: "Desarrollador Backend",
    industry: "technology",
    description: "Builds and maintains server-side logic, databases, and APIs.",
    descriptionEs: "Construye y mantiene la lógica del servidor, bases de datos y APIs.",
    aiCount: 378,
    tasks: ["api-development", "database-management", "server-optimization"],
  },
  {
    id: "full-stack-developer",
    name: "Full Stack Developer",
    nameEs: "Desarrollador Full Stack",
    industry: "technology",
    description: "Works on both frontend and backend development of applications.",
    descriptionEs: "Trabaja tanto en el desarrollo frontend como backend de aplicaciones.",
    aiCount: 489,
    tasks: ["web-development", "coding", "database-management", "api-development"],
  },
  {
    id: "mobile-developer",
    name: "Mobile Developer",
    nameEs: "Desarrollador Móvil",
    industry: "technology",
    description: "Develops applications for mobile devices and tablets.",
    descriptionEs: "Desarrolla aplicaciones para dispositivos móviles y tablets.",
    aiCount: 345,
    tasks: ["app-development", "mobile-app-design", "cross-platform-development"],
  },
  {
    id: "devops-engineer",
    name: "DevOps Engineer",
    nameEs: "Ingeniero DevOps",
    industry: "technology",
    description: "Manages development operations, CI/CD pipelines, and infrastructure.",
    descriptionEs: "Gestiona operaciones de desarrollo, pipelines CI/CD e infraestructura.",
    aiCount: 234,
    tasks: ["automation", "deployment", "monitoring", "cloud-management"],
  },
  {
    id: "data-scientist",
    name: "Data Scientist",
    nameEs: "Científico de Datos",
    industry: "technology",
    description: "Analyzes and interprets complex data to help organizations make decisions.",
    descriptionEs: "Analiza e interpreta datos complejos para ayudar a las organizaciones a tomar decisiones.",
    aiCount: 456,
    tasks: ["data-analysis", "machine-learning", "data-visualization", "predictive-modeling"],
  },
  {
    id: "ml-engineer",
    name: "ML Engineer",
    nameEs: "Ingeniero de ML",
    industry: "technology",
    description: "Designs and implements machine learning systems and models.",
    descriptionEs: "Diseña e implementa sistemas y modelos de machine learning.",
    aiCount: 378,
    tasks: ["machine-learning", "model-training", "ai-development", "algorithm-optimization"],
  },
  {
    id: "qa-engineer",
    name: "QA Engineer",
    nameEs: "Ingeniero de QA",
    industry: "technology",
    description: "Ensures software quality through testing and quality assurance processes.",
    descriptionEs: "Garantiza la calidad del software mediante pruebas y procesos de aseguramiento.",
    aiCount: 189,
    tasks: ["testing", "qa-testing", "automation", "bug-tracking"],
  },
  {
    id: "it-manager",
    name: "IT Manager",
    nameEs: "Gerente de TI",
    industry: "technology",
    description: "Manages IT infrastructure, systems, and technology teams.",
    descriptionEs: "Gestiona la infraestructura de TI, sistemas y equipos de tecnología.",
    aiCount: 234,
    tasks: ["project-management", "team-management", "infrastructure-planning"],
  },
  {
    id: "cybersecurity-analyst",
    name: "Cybersecurity Analyst",
    nameEs: "Analista de Ciberseguridad",
    industry: "technology",
    description: "Protects organizations from cyber threats and security breaches.",
    descriptionEs: "Protege a las organizaciones de amenazas cibernéticas y brechas de seguridad.",
    aiCount: 178,
    tasks: ["security-analysis", "threat-detection", "vulnerability-assessment"],
  },
  {
    id: "cloud-architect",
    name: "Cloud Architect",
    nameEs: "Arquitecto Cloud",
    industry: "technology",
    description: "Designs and implements cloud computing strategies and architectures.",
    descriptionEs: "Diseña e implementa estrategias y arquitecturas de computación en la nube.",
    aiCount: 145,
    tasks: ["cloud-design", "infrastructure-planning", "cloud-optimization"],
  },
  {
    id: "product-manager",
    name: "Product Manager",
    nameEs: "Gerente de Producto",
    industry: "technology",
    description: "Oversees product development from conception to launch and beyond.",
    descriptionEs: "Supervisa el desarrollo del producto desde la concepción hasta el lanzamiento.",
    aiCount: 289,
    tasks: ["product-development", "roadmap-planning", "user-research", "feature-prioritization"],
  },
  {
    id: "ux-designer",
    name: "UX Designer",
    nameEs: "Diseñador UX",
    industry: "technology",
    description: "Designs user experiences that are intuitive, accessible, and enjoyable.",
    descriptionEs: "Diseña experiencias de usuario intuitivas, accesibles y agradables.",
    aiCount: 312,
    tasks: ["ux-design", "user-research", "wireframing", "prototyping"],
  },
  {
    id: "ui-designer",
    name: "UI Designer",
    nameEs: "Diseñador UI",
    industry: "technology",
    description: "Creates visual designs and interactive elements for digital products.",
    descriptionEs: "Crea diseños visuales e elementos interactivos para productos digitales.",
    aiCount: 298,
    tasks: ["ui-design", "visual-design", "design-systems", "prototyping"],
  },

  // Healthcare
  {
    id: "doctor",
    name: "Doctor",
    nameEs: "Médico",
    industry: "healthcare",
    description: "Diagnoses and treats patients for various medical conditions.",
    descriptionEs: "Diagnostica y trata a pacientes con diversas condiciones médicas.",
    aiCount: 234,
    tasks: ["diagnosis", "treatment-planning", "medical-imaging", "patient-care"],
  },
  {
    id: "nurse",
    name: "Nurse",
    nameEs: "Enfermero/a",
    industry: "healthcare",
    description: "Provides patient care, administers medications, and supports doctors.",
    descriptionEs: "Proporciona atención al paciente, administra medicamentos y apoya a los médicos.",
    aiCount: 178,
    tasks: ["patient-care", "health-monitoring", "medication-management"],
  },
  {
    id: "medical-researcher",
    name: "Medical Researcher",
    nameEs: "Investigador Médico",
    industry: "healthcare",
    description: "Conducts research to advance medical knowledge and treatments.",
    descriptionEs: "Realiza investigaciones para avanzar en el conocimiento y tratamientos médicos.",
    aiCount: 189,
    tasks: ["research", "data-analysis", "clinical-trials", "paper-writing"],
  },
  {
    id: "pharmacist",
    name: "Pharmacist",
    nameEs: "Farmacéutico",
    industry: "healthcare",
    description: "Dispenses medications and provides drug-related information to patients.",
    descriptionEs: "Dispensa medicamentos y proporciona información sobre medicamentos a los pacientes.",
    aiCount: 89,
    tasks: ["medication-management", "drug-interactions", "prescription-review"],
  },
  {
    id: "therapist",
    name: "Therapist",
    nameEs: "Terapeuta",
    industry: "healthcare",
    description: "Provides mental health therapy and counseling services.",
    descriptionEs: "Proporciona terapia de salud mental y servicios de consejería.",
    aiCount: 123,
    tasks: ["mental-health", "counseling", "patient-assessment"],
  },
  {
    id: "physical-therapist",
    name: "Physical Therapist",
    nameEs: "Fisioterapeuta",
    industry: "healthcare",
    description: "Helps patients improve movement and manage pain through therapy.",
    descriptionEs: "Ayuda a los pacientes a mejorar el movimiento y manejar el dolor.",
    aiCount: 78,
    tasks: ["rehabilitation", "exercise-planning", "pain-management"],
  },
  {
    id: "nutritionist",
    name: "Nutritionist",
    nameEs: "Nutricionista",
    industry: "healthcare",
    description: "Provides dietary advice and creates nutrition plans for clients.",
    descriptionEs: "Proporciona consejos dietéticos y crea planes de nutrición.",
    aiCount: 145,
    tasks: ["meal-planning", "nutrition-analysis", "diet-consultation"],
  },
  {
    id: "veterinarian",
    name: "Veterinarian",
    nameEs: "Veterinario",
    industry: "healthcare",
    description: "Diagnoses and treats animals for various health conditions.",
    descriptionEs: "Diagnostica y trata animales con diversas condiciones de salud.",
    aiCount: 67,
    tasks: ["animal-care", "diagnosis", "treatment-planning"],
  },

  // Finance
  {
    id: "accountant",
    name: "Accountant",
    nameEs: "Contador",
    industry: "finance",
    description: "Prepares and examines financial records and statements.",
    descriptionEs: "Prepara y examina registros y estados financieros.",
    aiCount: 234,
    tasks: ["accounting", "financial-reporting", "tax-preparation", "audit"],
  },
  {
    id: "financial-analyst",
    name: "Financial Analyst",
    nameEs: "Analista Financiero",
    industry: "finance",
    description: "Analyzes financial data and provides investment recommendations.",
    descriptionEs: "Analiza datos financieros y proporciona recomendaciones de inversión.",
    aiCount: 289,
    tasks: ["financial-analysis", "investment-analysis", "market-research"],
  },
  {
    id: "investment-banker",
    name: "Investment Banker",
    nameEs: "Banquero de Inversión",
    industry: "finance",
    description: "Advises on mergers, acquisitions, and capital raising.",
    descriptionEs: "Asesora sobre fusiones, adquisiciones y recaudación de capital.",
    aiCount: 178,
    tasks: ["valuation", "due-diligence", "deal-structuring"],
  },
  {
    id: "trader",
    name: "Trader",
    nameEs: "Trader",
    industry: "finance",
    description: "Buys and sells securities, commodities, and currencies.",
    descriptionEs: "Compra y vende valores, materias primas y divisas.",
    aiCount: 234,
    tasks: ["trading", "market-analysis", "risk-management"],
  },
  {
    id: "tax-advisor",
    name: "Tax Advisor",
    nameEs: "Asesor Fiscal",
    industry: "finance",
    description: "Provides tax planning and compliance advice to individuals and businesses.",
    descriptionEs: "Proporciona asesoramiento de planificación fiscal.",
    aiCount: 145,
    tasks: ["tax-preparation", "tax-planning", "compliance"],
  },
  {
    id: "wealth-manager",
    name: "Wealth Manager",
    nameEs: "Gestor de Patrimonio",
    industry: "finance",
    description: "Manages investments and financial planning for wealthy clients.",
    descriptionEs: "Gestiona inversiones y planificación financiera para clientes adinerados.",
    aiCount: 156,
    tasks: ["investment-management", "financial-planning", "portfolio-optimization"],
  },
  {
    id: "insurance-agent",
    name: "Insurance Agent",
    nameEs: "Agente de Seguros",
    industry: "finance",
    description: "Sells and manages insurance policies for clients.",
    descriptionEs: "Vende y gestiona pólizas de seguros para clientes.",
    aiCount: 89,
    tasks: ["policy-analysis", "risk-assessment", "customer-service"],
  },

  // Education
  {
    id: "teacher",
    name: "Teacher",
    nameEs: "Profesor",
    industry: "education",
    description: "Educates students and facilitates learning in various subjects.",
    descriptionEs: "Educa a los estudiantes y facilita el aprendizaje en diversas materias.",
    aiCount: 345,
    tasks: ["teaching", "lesson-planning", "grading", "curriculum-development"],
  },
  {
    id: "professor",
    name: "Professor",
    nameEs: "Catedrático",
    industry: "education",
    description: "Teaches at universities and conducts academic research.",
    descriptionEs: "Enseña en universidades y realiza investigaciones académicas.",
    aiCount: 267,
    tasks: ["teaching", "research", "paper-writing", "curriculum-development"],
  },
  {
    id: "tutor",
    name: "Tutor",
    nameEs: "Tutor",
    industry: "education",
    description: "Provides one-on-one educational support to students.",
    descriptionEs: "Proporciona apoyo educativo individual a los estudiantes.",
    aiCount: 189,
    tasks: ["tutoring", "homework-help", "test-preparation"],
  },
  {
    id: "instructional-designer",
    name: "Instructional Designer",
    nameEs: "Diseñador Instruccional",
    industry: "education",
    description: "Creates educational materials and learning experiences.",
    descriptionEs: "Crea materiales educativos y experiencias de aprendizaje.",
    aiCount: 178,
    tasks: ["course-creation", "curriculum-design", "e-learning-development"],
  },
  {
    id: "school-counselor",
    name: "School Counselor",
    nameEs: "Consejero Escolar",
    industry: "education",
    description: "Provides academic and personal guidance to students.",
    descriptionEs: "Proporciona orientación académica y personal a los estudiantes.",
    aiCount: 89,
    tasks: ["counseling", "career-guidance", "student-support"],
  },

  // Marketing
  {
    id: "marketing-manager",
    name: "Marketing Manager",
    nameEs: "Gerente de Marketing",
    industry: "marketing",
    description: "Plans and executes marketing strategies and campaigns.",
    descriptionEs: "Planifica y ejecuta estrategias y campañas de marketing.",
    aiCount: 456,
    tasks: ["marketing-strategy", "campaign-management", "branding", "analytics"],
  },
  {
    id: "social-media-manager",
    name: "Social Media Manager",
    nameEs: "Community Manager",
    industry: "marketing",
    description: "Manages social media presence and creates content.",
    descriptionEs: "Gestiona la presencia en redes sociales y crea contenido.",
    aiCount: 378,
    tasks: ["social-media", "content-creation", "community-management"],
  },
  {
    id: "content-marketer",
    name: "Content Marketer",
    nameEs: "Marketer de Contenido",
    industry: "marketing",
    description: "Creates and distributes valuable content to attract audiences.",
    descriptionEs: "Crea y distribuye contenido valioso para atraer audiencias.",
    aiCount: 345,
    tasks: ["content-creation", "blog-writing", "seo", "content-strategy"],
  },
  {
    id: "seo-specialist",
    name: "SEO Specialist",
    nameEs: "Especialista SEO",
    industry: "marketing",
    description: "Optimizes websites to rank higher in search engine results.",
    descriptionEs: "Optimiza sitios web para clasificar mejor en resultados de búsqueda.",
    aiCount: 289,
    tasks: ["seo-optimization", "keyword-research", "link-building", "analytics"],
  },
  {
    id: "email-marketer",
    name: "Email Marketer",
    nameEs: "Marketer de Email",
    industry: "marketing",
    description: "Creates and manages email marketing campaigns.",
    descriptionEs: "Crea y gestiona campañas de email marketing.",
    aiCount: 234,
    tasks: ["email-marketing", "email-automation", "campaign-optimization"],
  },
  {
    id: "brand-manager",
    name: "Brand Manager",
    nameEs: "Gerente de Marca",
    industry: "marketing",
    description: "Develops and maintains brand identity and strategy.",
    descriptionEs: "Desarrolla y mantiene la identidad y estrategia de marca.",
    aiCount: 189,
    tasks: ["branding", "brand-strategy", "market-research"],
  },
  {
    id: "pr-specialist",
    name: "PR Specialist",
    nameEs: "Especialista en PR",
    industry: "marketing",
    description: "Manages public relations and media communications.",
    descriptionEs: "Gestiona relaciones públicas y comunicaciones de medios.",
    aiCount: 145,
    tasks: ["public-relations", "media-relations", "press-releases"],
  },
  {
    id: "growth-hacker",
    name: "Growth Hacker",
    nameEs: "Growth Hacker",
    industry: "marketing",
    description: "Uses data-driven techniques to grow user base rapidly.",
    descriptionEs: "Usa técnicas basadas en datos para crecer la base de usuarios.",
    aiCount: 234,
    tasks: ["growth-hacking", "a-b-testing", "analytics", "user-acquisition"],
  },

  // Design
  {
    id: "graphic-designer",
    name: "Graphic Designer",
    nameEs: "Diseñador Gráfico",
    industry: "design",
    description: "Creates visual concepts to communicate ideas and messages.",
    descriptionEs: "Crea conceptos visuales para comunicar ideas y mensajes.",
    aiCount: 456,
    tasks: ["graphic-design", "logo-design", "branding", "print-design"],
  },
  {
    id: "web-designer",
    name: "Web Designer",
    nameEs: "Diseñador Web",
    industry: "design",
    description: "Designs websites and web applications for optimal user experience.",
    descriptionEs: "Diseña sitios web y aplicaciones web para una experiencia óptima.",
    aiCount: 378,
    tasks: ["web-design", "ui-design", "responsive-design"],
  },
  {
    id: "illustrator",
    name: "Illustrator",
    nameEs: "Ilustrador",
    industry: "design",
    description: "Creates original artwork and illustrations for various media.",
    descriptionEs: "Crea obras de arte e ilustraciones originales para diversos medios.",
    aiCount: 289,
    tasks: ["illustration", "art-generation", "character-design"],
  },
  {
    id: "motion-designer",
    name: "Motion Designer",
    nameEs: "Diseñador de Motion",
    industry: "design",
    description: "Creates animated graphics and visual effects.",
    descriptionEs: "Crea gráficos animados y efectos visuales.",
    aiCount: 234,
    tasks: ["animation", "motion-graphics", "video-editing"],
  },
  {
    id: "fashion-designer",
    name: "Fashion Designer",
    nameEs: "Diseñador de Moda",
    industry: "design",
    description: "Designs clothing, accessories, and fashion collections.",
    descriptionEs: "Diseña ropa, accesorios y colecciones de moda.",
    aiCount: 156,
    tasks: ["fashion-design", "pattern-design", "collection-planning"],
  },
  {
    id: "interior-designer",
    name: "Interior Designer",
    nameEs: "Diseñador de Interiores",
    industry: "design",
    description: "Designs indoor spaces for functionality and aesthetics.",
    descriptionEs: "Diseña espacios interiores para funcionalidad y estética.",
    aiCount: 178,
    tasks: ["interior-design", "space-planning", "3d-modeling"],
  },
  {
    id: "architect",
    name: "Architect",
    nameEs: "Arquitecto",
    industry: "design",
    description: "Designs buildings and oversees construction projects.",
    descriptionEs: "Diseña edificios y supervisa proyectos de construcción.",
    aiCount: 189,
    tasks: ["architectural-design", "3d-modeling", "blueprint-creation"],
  },
  {
    id: "logo-designer",
    name: "Logo Designer",
    nameEs: "Diseñador de Logos",
    industry: "design",
    description: "Creates visual identities and logos for brands.",
    descriptionEs: "Crea identidades visuales y logos para marcas.",
    aiCount: 234,
    tasks: ["logo-design", "branding", "visual-identity"],
  },

  // Business
  {
    id: "ceo",
    name: "CEO",
    nameEs: "CEO",
    industry: "business",
    description: "Leads the company and makes major corporate decisions.",
    descriptionEs: "Lidera la empresa y toma decisiones corporativas importantes.",
    aiCount: 178,
    tasks: ["strategic-planning", "decision-making", "leadership"],
  },
  {
    id: "entrepreneur",
    name: "Entrepreneur",
    nameEs: "Emprendedor",
    industry: "business",
    description: "Starts and manages new business ventures.",
    descriptionEs: "Inicia y gestiona nuevos proyectos empresariales.",
    aiCount: 234,
    tasks: ["business-planning", "fundraising", "product-development"],
  },
  {
    id: "project-manager",
    name: "Project Manager",
    nameEs: "Gerente de Proyecto",
    industry: "business",
    description: "Plans, executes, and closes projects within organizations.",
    descriptionEs: "Planifica, ejecuta y cierra proyectos dentro de las organizaciones.",
    aiCount: 312,
    tasks: ["project-management", "planning", "team-coordination", "resource-allocation"],
  },
  {
    id: "consultant",
    name: "Consultant",
    nameEs: "Consultor",
    industry: "business",
    description: "Provides expert advice to organizations in specific areas.",
    descriptionEs: "Proporciona asesoramiento experto a organizaciones en áreas específicas.",
    aiCount: 189,
    tasks: ["analysis", "strategy", "problem-solving", "recommendations"],
  },
  {
    id: "business-analyst",
    name: "Business Analyst",
    nameEs: "Analista de Negocios",
    industry: "business",
    description: "Analyzes business processes and recommends improvements.",
    descriptionEs: "Analiza procesos de negocio y recomienda mejoras.",
    aiCount: 267,
    tasks: ["business-analysis", "process-optimization", "requirements-gathering"],
  },
  {
    id: "operations-manager",
    name: "Operations Manager",
    nameEs: "Gerente de Operaciones",
    industry: "business",
    description: "Oversees day-to-day business operations and processes.",
    descriptionEs: "Supervisa las operaciones y procesos diarios del negocio.",
    aiCount: 178,
    tasks: ["operations-management", "process-optimization", "team-management"],
  },
  {
    id: "executive-assistant",
    name: "Executive Assistant",
    nameEs: "Asistente Ejecutivo",
    industry: "business",
    description: "Provides administrative support to executives.",
    descriptionEs: "Proporciona apoyo administrativo a ejecutivos.",
    aiCount: 145,
    tasks: ["scheduling", "email-management", "travel-planning", "document-preparation"],
  },

  // Legal
  {
    id: "lawyer",
    name: "Lawyer",
    nameEs: "Abogado",
    industry: "legal",
    description: "Provides legal advice and represents clients in legal matters.",
    descriptionEs: "Proporciona asesoramiento legal y representa clientes en asuntos legales.",
    aiCount: 189,
    tasks: ["legal-research", "contract-analysis", "document-drafting", "litigation"],
  },
  {
    id: "paralegal",
    name: "Paralegal",
    nameEs: "Paralegal",
    industry: "legal",
    description: "Assists lawyers with legal research and document preparation.",
    descriptionEs: "Asiste a abogados con investigación legal y preparación de documentos.",
    aiCount: 123,
    tasks: ["legal-research", "document-preparation", "case-management"],
  },
  {
    id: "compliance-officer",
    name: "Compliance Officer",
    nameEs: "Oficial de Cumplimiento",
    industry: "legal",
    description: "Ensures organizations comply with laws and regulations.",
    descriptionEs: "Garantiza que las organizaciones cumplan con leyes y regulaciones.",
    aiCount: 89,
    tasks: ["compliance-checking", "policy-review", "risk-assessment"],
  },
  {
    id: "contract-manager",
    name: "Contract Manager",
    nameEs: "Gestor de Contratos",
    industry: "legal",
    description: "Manages contracts throughout their lifecycle.",
    descriptionEs: "Gestiona contratos durante todo su ciclo de vida.",
    aiCount: 78,
    tasks: ["contract-analysis", "negotiation", "document-management"],
  },

  // Creative
  {
    id: "writer",
    name: "Writer",
    nameEs: "Escritor",
    industry: "creative",
    description: "Creates written content for various media and publications.",
    descriptionEs: "Crea contenido escrito para diversos medios y publicaciones.",
    aiCount: 456,
    tasks: ["writing", "editing", "content-creation", "creative-writing"],
  },
  {
    id: "copywriter",
    name: "Copywriter",
    nameEs: "Copywriter",
    industry: "creative",
    description: "Writes persuasive text for advertising and marketing.",
    descriptionEs: "Escribe textos persuasivos para publicidad y marketing.",
    aiCount: 378,
    tasks: ["copywriting", "ad-copy", "marketing-content", "headline-writing"],
  },
  {
    id: "screenwriter",
    name: "Screenwriter",
    nameEs: "Guionista",
    industry: "creative",
    description: "Writes scripts for films, television, and other media.",
    descriptionEs: "Escribe guiones para películas, televisión y otros medios.",
    aiCount: 189,
    tasks: ["script-writing", "story-development", "dialogue-writing"],
  },
  {
    id: "video-editor",
    name: "Video Editor",
    nameEs: "Editor de Video",
    industry: "creative",
    description: "Edits and assembles video footage into finished products.",
    descriptionEs: "Edita y ensambla material de video en productos terminados.",
    aiCount: 345,
    tasks: ["video-editing", "color-grading", "motion-graphics", "audio-editing"],
  },
  {
    id: "photographer",
    name: "Photographer",
    nameEs: "Fotógrafo",
    industry: "creative",
    description: "Captures and edits photographs for various purposes.",
    descriptionEs: "Captura y edita fotografías para diversos propósitos.",
    aiCount: 289,
    tasks: ["photography", "photo-editing", "image-enhancement"],
  },
  {
    id: "musician",
    name: "Musician",
    nameEs: "Músico",
    industry: "creative",
    description: "Creates, performs, and produces music.",
    descriptionEs: "Crea, interpreta y produce música.",
    aiCount: 234,
    tasks: ["music-composition", "music-production", "audio-editing"],
  },
  {
    id: "voice-actor",
    name: "Voice Actor",
    nameEs: "Actor de Voz",
    industry: "creative",
    description: "Provides voice performances for various media.",
    descriptionEs: "Proporciona actuaciones de voz para diversos medios.",
    aiCount: 178,
    tasks: ["voice-over", "audio-recording", "character-voice"],
  },
  {
    id: "game-designer",
    name: "Game Designer",
    nameEs: "Diseñador de Juegos",
    industry: "creative",
    description: "Designs gameplay mechanics and experiences for video games.",
    descriptionEs: "Diseña mecánicas de juego y experiencias para videojuegos.",
    aiCount: 267,
    tasks: ["game-design", "level-design", "narrative-design", "prototyping"],
  },
  {
    id: "animator",
    name: "Animator",
    nameEs: "Animador",
    industry: "creative",
    description: "Creates animations for films, games, and other media.",
    descriptionEs: "Crea animaciones para películas, juegos y otros medios.",
    aiCount: 234,
    tasks: ["animation", "3d-modeling", "rigging", "storyboarding"],
  },
  {
    id: "podcaster",
    name: "Podcaster",
    nameEs: "Podcaster",
    industry: "creative",
    description: "Creates and produces audio content in podcast format.",
    descriptionEs: "Crea y produce contenido de audio en formato podcast.",
    aiCount: 189,
    tasks: ["podcast-creation", "audio-editing", "content-planning"],
  },

  // Engineering
  {
    id: "mechanical-engineer",
    name: "Mechanical Engineer",
    nameEs: "Ingeniero Mecánico",
    industry: "engineering",
    description: "Designs and develops mechanical systems and products.",
    descriptionEs: "Diseña y desarrolla sistemas y productos mecánicos.",
    aiCount: 178,
    tasks: ["cad-design", "simulation", "prototyping", "product-design"],
  },
  {
    id: "electrical-engineer",
    name: "Electrical Engineer",
    nameEs: "Ingeniero Eléctrico",
    industry: "engineering",
    description: "Designs and develops electrical systems and components.",
    descriptionEs: "Diseña y desarrolla sistemas y componentes eléctricos.",
    aiCount: 156,
    tasks: ["circuit-design", "simulation", "testing", "documentation"],
  },
  {
    id: "civil-engineer",
    name: "Civil Engineer",
    nameEs: "Ingeniero Civil",
    industry: "engineering",
    description: "Designs and oversees construction projects.",
    descriptionEs: "Diseña y supervisa proyectos de construcción.",
    aiCount: 134,
    tasks: ["structural-design", "project-management", "blueprint-review"],
  },

  // Sales
  {
    id: "sales-representative",
    name: "Sales Representative",
    nameEs: "Representante de Ventas",
    industry: "sales",
    description: "Sells products and services to customers.",
    descriptionEs: "Vende productos y servicios a clientes.",
    aiCount: 234,
    tasks: ["sales", "lead-generation", "customer-service", "negotiation"],
  },
  {
    id: "account-manager",
    name: "Account Manager",
    nameEs: "Account Manager",
    industry: "sales",
    description: "Manages client relationships and accounts.",
    descriptionEs: "Gestiona relaciones con clientes y cuentas.",
    aiCount: 189,
    tasks: ["client-management", "upselling", "customer-success"],
  },
  {
    id: "sales-manager",
    name: "Sales Manager",
    nameEs: "Gerente de Ventas",
    industry: "sales",
    description: "Leads sales teams and develops sales strategies.",
    descriptionEs: "Lidera equipos de ventas y desarrolla estrategias de ventas.",
    aiCount: 178,
    tasks: ["sales-strategy", "team-management", "forecasting", "training"],
  },

  // HR
  {
    id: "hr-manager",
    name: "HR Manager",
    nameEs: "Gerente de RRHH",
    industry: "hr",
    description: "Manages human resources functions and policies.",
    descriptionEs: "Gestiona funciones y políticas de recursos humanos.",
    aiCount: 234,
    tasks: ["recruitment", "employee-relations", "performance-management", "policy-development"],
  },
  {
    id: "recruiter",
    name: "Recruiter",
    nameEs: "Reclutador",
    industry: "hr",
    description: "Sources and hires candidates for job positions.",
    descriptionEs: "Busca y contrata candidatos para puestos de trabajo.",
    aiCount: 189,
    tasks: ["recruiting", "candidate-screening", "interviewing", "onboarding"],
  },
  {
    id: "training-manager",
    name: "Training Manager",
    nameEs: "Gerente de Capacitación",
    industry: "hr",
    description: "Develops and implements employee training programs.",
    descriptionEs: "Desarrolla e implementa programas de capacitación.",
    aiCount: 145,
    tasks: ["training-development", "course-creation", "employee-onboarding"],
  },

  // Media
  {
    id: "journalist",
    name: "Journalist",
    nameEs: "Periodista",
    industry: "media",
    description: "Researches and reports news and stories.",
    descriptionEs: "Investiga y reporta noticias e historias.",
    aiCount: 234,
    tasks: ["news-writing", "research", "interviewing", "fact-checking"],
  },
  {
    id: "video-producer",
    name: "Video Producer",
    nameEs: "Productor de Video",
    industry: "media",
    description: "Oversees video production from concept to delivery.",
    descriptionEs: "Supervisa la producción de video desde el concepto hasta la entrega.",
    aiCount: 267,
    tasks: ["video-production", "project-management", "storyboarding", "editing"],
  },
  {
    id: "content-creator",
    name: "Content Creator",
    nameEs: "Creador de Contenido",
    industry: "media",
    description: "Creates content for social media, websites, and platforms.",
    descriptionEs: "Crea contenido para redes sociales, sitios web y plataformas.",
    aiCount: 389,
    tasks: ["content-creation", "video-creation", "social-media", "editing"],
  },
  {
    id: "streamer",
    name: "Streamer",
    nameEs: "Streamer",
    industry: "media",
    description: "Creates live streaming content for online audiences.",
    descriptionEs: "Crea contenido de streaming en vivo para audiencias en línea.",
    aiCount: 178,
    tasks: ["live-streaming", "content-planning", "audience-engagement"],
  },

  // Science
  {
    id: "researcher",
    name: "Researcher",
    nameEs: "Investigador",
    industry: "science",
    description: "Conducts research in academic or industry settings.",
    descriptionEs: "Realiza investigaciones en entornos académicos o industriales.",
    aiCount: 289,
    tasks: ["research", "data-analysis", "paper-writing", "experimentation"],
  },
  {
    id: "biologist",
    name: "Biologist",
    nameEs: "Biólogo",
    industry: "science",
    description: "Studies living organisms and biological processes.",
    descriptionEs: "Estudia organismos vivos y procesos biológicos.",
    aiCount: 156,
    tasks: ["research", "data-analysis", "lab-work", "documentation"],
  },
  {
    id: "chemist",
    name: "Chemist",
    nameEs: "Químico",
    industry: "science",
    description: "Studies chemical substances and reactions.",
    descriptionEs: "Estudia sustancias químicas y reacciones.",
    aiCount: 123,
    tasks: ["research", "experimentation", "data-analysis", "reporting"],
  },

  // Services
  {
    id: "real-estate-agent",
    name: "Real Estate Agent",
    nameEs: "Agente Inmobiliario",
    industry: "services",
    description: "Helps clients buy, sell, and rent properties.",
    descriptionEs: "Ayuda a clientes a comprar, vender y alquilar propiedades.",
    aiCount: 145,
    tasks: ["property-listing", "client-management", "market-analysis"],
  },
  {
    id: "event-planner",
    name: "Event Planner",
    nameEs: "Planificador de Eventos",
    industry: "services",
    description: "Plans and coordinates events and gatherings.",
    descriptionEs: "Planifica y coordina eventos y reuniones.",
    aiCount: 178,
    tasks: ["event-planning", "vendor-management", "scheduling", "budget-management"],
  },
  {
    id: "travel-agent",
    name: "Travel Agent",
    nameEs: "Agente de Viajes",
    industry: "services",
    description: "Plans and books travel arrangements for clients.",
    descriptionEs: "Planifica y reserva arreglos de viaje para clientes.",
    aiCount: 89,
    tasks: ["travel-planning", "booking", "itinerary-creation"],
  },
  {
    id: "chef",
    name: "Chef",
    nameEs: "Chef",
    industry: "services",
    description: "Prepares and creates culinary dishes and menus.",
    descriptionEs: "Prepara y crea platos culinarios y menús.",
    aiCount: 123,
    tasks: ["recipe-development", "menu-planning", "food-presentation"],
  },
  {
    id: "personal-trainer",
    name: "Personal Trainer",
    nameEs: "Entrenador Personal",
    industry: "services",
    description: "Designs and leads fitness programs for clients.",
    descriptionEs: "Diseña y lidera programas de fitness para clientes.",
    aiCount: 145,
    tasks: ["fitness-planning", "workout-design", "nutrition-advice"],
  },
];

// Helper functions
export function getProfessionsByIndustry(industry: IndustryType): Profession[] {
  return professions.filter(prof => prof.industry === industry);
}

export function searchProfessions(query: string): Profession[] {
  const lowerQuery = query.toLowerCase();
  return professions.filter(prof => 
    prof.name.toLowerCase().includes(lowerQuery) ||
    prof.nameEs.toLowerCase().includes(lowerQuery) ||
    prof.description.toLowerCase().includes(lowerQuery)
  );
}

export function getProfessionById(id: string): Profession | undefined {
  return professions.find(prof => prof.id === id);
}

export const totalProfessionsCount = professions.length;
