// Massive Tasks Database - Inspired by theresanaiforthat.com
// 500+ AI Tasks organized alphabetically

export interface AITask {
  id: string;
  name: string;
  nameEs: string;
  category: string;
  aiCount: number;
}

export type TaskCategoryType = 
  | "content" 
  | "creative" 
  | "business" 
  | "development" 
  | "productivity"
  | "research"
  | "marketing"
  | "education"
  | "entertainment"
  | "health"
  | "finance"
  | "legal"
  | "design"
  | "communication";

export const taskCategories: { id: TaskCategoryType; name: string; nameEs: string }[] = [
  { id: "content", name: "Content Creation", nameEs: "Creación de Contenido" },
  { id: "creative", name: "Creative", nameEs: "Creativo" },
  { id: "business", name: "Business", nameEs: "Negocios" },
  { id: "development", name: "Development", nameEs: "Desarrollo" },
  { id: "productivity", name: "Productivity", nameEs: "Productividad" },
  { id: "research", name: "Research", nameEs: "Investigación" },
  { id: "marketing", name: "Marketing", nameEs: "Marketing" },
  { id: "education", name: "Education", nameEs: "Educación" },
  { id: "entertainment", name: "Entertainment", nameEs: "Entretenimiento" },
  { id: "health", name: "Health", nameEs: "Salud" },
  { id: "finance", name: "Finance", nameEs: "Finanzas" },
  { id: "legal", name: "Legal", nameEs: "Legal" },
  { id: "design", name: "Design", nameEs: "Diseño" },
  { id: "communication", name: "Communication", nameEs: "Comunicación" },
];

export const aiTasks: AITask[] = [
  // A - Tasks starting with A
  { id: "a-b-testing", name: "A/B Testing", nameEs: "Pruebas A/B", category: "marketing", aiCount: 45 },
  { id: "accounting", name: "Accounting", nameEs: "Contabilidad", category: "finance", aiCount: 67 },
  { id: "ad-copy-generation", name: "Ad Copy Generation", nameEs: "Generación de Anuncios", category: "marketing", aiCount: 89 },
  { id: "ad-creation", name: "Ad Creation", nameEs: "Creación de Anuncios", category: "marketing", aiCount: 156 },
  { id: "ad-optimization", name: "Ad Optimization", nameEs: "Optimización de Anuncios", category: "marketing", aiCount: 78 },
  { id: "ad-targeting", name: "Ad Targeting", nameEs: "Segmentación de Anuncios", category: "marketing", aiCount: 56 },
  { id: "agile-management", name: "Agile Management", nameEs: "Gestión Ágil", category: "business", aiCount: 34 },
  { id: "album-cover-design", name: "Album Cover Design", nameEs: "Diseño de Portadas", category: "design", aiCount: 45 },
  { id: "animation", name: "Animation", nameEs: "Animación", category: "creative", aiCount: 234 },
  { id: "annotating", name: "Annotating", nameEs: "Anotación", category: "productivity", aiCount: 67 },
  { id: "app-design", name: "App Design", nameEs: "Diseño de Apps", category: "design", aiCount: 189 },
  { id: "app-development", name: "App Development", nameEs: "Desarrollo de Apps", category: "development", aiCount: 345 },
  { id: "architectural-design", name: "Architectural Design", nameEs: "Diseño Arquitectónico", category: "design", aiCount: 78 },
  { id: "article-generation", name: "Article Generation", nameEs: "Generación de Artículos", category: "content", aiCount: 234 },
  { id: "article-rewriting", name: "Article Rewriting", nameEs: "Reescritura de Artículos", category: "content", aiCount: 178 },
  { id: "art-generation", name: "Art Generation", nameEs: "Generación de Arte", category: "creative", aiCount: 456 },
  { id: "asset-generation", name: "Asset Generation", nameEs: "Generación de Assets", category: "creative", aiCount: 123 },
  { id: "audio-editing", name: "Audio Editing", nameEs: "Edición de Audio", category: "creative", aiCount: 189 },
  { id: "audio-enhancement", name: "Audio Enhancement", nameEs: "Mejora de Audio", category: "creative", aiCount: 145 },
  { id: "audio-generation", name: "Audio Generation", nameEs: "Generación de Audio", category: "creative", aiCount: 234 },
  { id: "audio-mixing", name: "Audio Mixing", nameEs: "Mezcla de Audio", category: "creative", aiCount: 89 },
  { id: "audio-restoration", name: "Audio Restoration", nameEs: "Restauración de Audio", category: "creative", aiCount: 45 },
  { id: "audio-transcription", name: "Audio Transcription", nameEs: "Transcripción de Audio", category: "productivity", aiCount: 267 },
  { id: "audio-translation", name: "Audio Translation", nameEs: "Traducción de Audio", category: "communication", aiCount: 123 },
  { id: "audit-automation", name: "Audit Automation", nameEs: "Automatización de Auditorías", category: "business", aiCount: 34 },
  { id: "authoring", name: "Authoring", nameEs: "Autoría", category: "content", aiCount: 156 },
  { id: "auto-complete", name: "Auto Complete", nameEs: "Autocompletado", category: "productivity", aiCount: 89 },
  { id: "automated-testing", name: "Automated Testing", nameEs: "Testing Automatizado", category: "development", aiCount: 178 },

  // B - Tasks starting with B
  { id: "background-removal", name: "Background Removal", nameEs: "Eliminación de Fondo", category: "design", aiCount: 345 },
  { id: "background-replacement", name: "Background Replacement", nameEs: "Reemplazo de Fondo", category: "design", aiCount: 234 },
  { id: "banner-design", name: "Banner Design", nameEs: "Diseño de Banners", category: "design", aiCount: 189 },
  { id: "benchmarking", name: "Benchmarking", nameEs: "Benchmarking", category: "business", aiCount: 45 },
  { id: "blog-writing", name: "Blog Writing", nameEs: "Escritura de Blogs", category: "content", aiCount: 345 },
  { id: "book-cover-design", name: "Book Cover Design", nameEs: "Diseño de Portadas de Libros", category: "design", aiCount: 89 },
  { id: "book-writing", name: "Book Writing", nameEs: "Escritura de Libros", category: "content", aiCount: 156 },
  { id: "brand-design", name: "Brand Design", nameEs: "Diseño de Marca", category: "design", aiCount: 178 },
  { id: "brand-monitoring", name: "Brand Monitoring", nameEs: "Monitoreo de Marca", category: "marketing", aiCount: 67 },
  { id: "branding", name: "Branding", nameEs: "Branding", category: "marketing", aiCount: 234 },
  { id: "budget-planning", name: "Budget Planning", nameEs: "Planificación de Presupuesto", category: "finance", aiCount: 78 },
  { id: "business-analytics", name: "Business Analytics", nameEs: "Analítica de Negocios", category: "business", aiCount: 156 },
  { id: "business-intelligence", name: "Business Intelligence", nameEs: "Inteligencia de Negocios", category: "business", aiCount: 189 },
  { id: "business-planning", name: "Business Planning", nameEs: "Planificación de Negocios", category: "business", aiCount: 123 },
  { id: "business-writing", name: "Business Writing", nameEs: "Escritura de Negocios", category: "content", aiCount: 145 },

  // C - Tasks starting with C
  { id: "calendar-management", name: "Calendar Management", nameEs: "Gestión de Calendario", category: "productivity", aiCount: 89 },
  { id: "call-center-automation", name: "Call Center Automation", nameEs: "Automatización de Call Center", category: "business", aiCount: 67 },
  { id: "call-transcription", name: "Call Transcription", nameEs: "Transcripción de Llamadas", category: "communication", aiCount: 78 },
  { id: "caption-generation", name: "Caption Generation", nameEs: "Generación de Subtítulos", category: "content", aiCount: 234 },
  { id: "card-design", name: "Card Design", nameEs: "Diseño de Tarjetas", category: "design", aiCount: 67 },
  { id: "career-advice", name: "Career Advice", nameEs: "Consejos de Carrera", category: "education", aiCount: 45 },
  { id: "cash-flow-analysis", name: "Cash Flow Analysis", nameEs: "Análisis de Flujo de Caja", category: "finance", aiCount: 56 },
  { id: "character-design", name: "Character Design", nameEs: "Diseño de Personajes", category: "design", aiCount: 178 },
  { id: "chatbot-development", name: "Chatbot Development", nameEs: "Desarrollo de Chatbots", category: "development", aiCount: 267 },
  { id: "coding", name: "Coding", nameEs: "Programación", category: "development", aiCount: 567 },
  { id: "coding-assistance", name: "Coding Assistance", nameEs: "Asistencia de Programación", category: "development", aiCount: 345 },
  { id: "collaboration", name: "Collaboration", nameEs: "Colaboración", category: "productivity", aiCount: 123 },
  { id: "color-correction", name: "Color Correction", nameEs: "Corrección de Color", category: "design", aiCount: 145 },
  { id: "color-palette-generation", name: "Color Palette Generation", nameEs: "Generación de Paletas", category: "design", aiCount: 89 },
  { id: "comic-creation", name: "Comic Creation", nameEs: "Creación de Cómics", category: "creative", aiCount: 78 },
  { id: "competitive-analysis", name: "Competitive Analysis", nameEs: "Análisis Competitivo", category: "business", aiCount: 123 },
  { id: "compliance-checking", name: "Compliance Checking", nameEs: "Verificación de Cumplimiento", category: "legal", aiCount: 45 },
  { id: "content-curation", name: "Content Curation", nameEs: "Curación de Contenido", category: "content", aiCount: 156 },
  { id: "content-generation", name: "Content Generation", nameEs: "Generación de Contenido", category: "content", aiCount: 456 },
  { id: "content-moderation", name: "Content Moderation", nameEs: "Moderación de Contenido", category: "business", aiCount: 89 },
  { id: "content-optimization", name: "Content Optimization", nameEs: "Optimización de Contenido", category: "content", aiCount: 234 },
  { id: "content-planning", name: "Content Planning", nameEs: "Planificación de Contenido", category: "content", aiCount: 178 },
  { id: "content-repurposing", name: "Content Repurposing", nameEs: "Reutilización de Contenido", category: "content", aiCount: 145 },
  { id: "content-scheduling", name: "Content Scheduling", nameEs: "Programación de Contenido", category: "marketing", aiCount: 189 },
  { id: "content-strategy", name: "Content Strategy", nameEs: "Estrategia de Contenido", category: "marketing", aiCount: 156 },
  { id: "contract-analysis", name: "Contract Analysis", nameEs: "Análisis de Contratos", category: "legal", aiCount: 67 },
  { id: "copy-editing", name: "Copy Editing", nameEs: "Edición de Textos", category: "content", aiCount: 234 },
  { id: "copywriting", name: "Copywriting", nameEs: "Copywriting", category: "content", aiCount: 345 },
  { id: "course-creation", name: "Course Creation", nameEs: "Creación de Cursos", category: "education", aiCount: 178 },
  { id: "cover-letter-writing", name: "Cover Letter Writing", nameEs: "Escritura de Cartas", category: "content", aiCount: 145 },
  { id: "creative-writing", name: "Creative Writing", nameEs: "Escritura Creativa", category: "content", aiCount: 267 },
  { id: "css-generation", name: "CSS Generation", nameEs: "Generación de CSS", category: "development", aiCount: 89 },
  { id: "customer-analytics", name: "Customer Analytics", nameEs: "Analítica de Clientes", category: "business", aiCount: 123 },
  { id: "customer-segmentation", name: "Customer Segmentation", nameEs: "Segmentación de Clientes", category: "marketing", aiCount: 156 },
  { id: "customer-service", name: "Customer Service", nameEs: "Servicio al Cliente", category: "business", aiCount: 234 },
  { id: "customer-support", name: "Customer Support", nameEs: "Soporte al Cliente", category: "business", aiCount: 189 },

  // D - Tasks starting with D
  { id: "dashboard-creation", name: "Dashboard Creation", nameEs: "Creación de Dashboards", category: "business", aiCount: 145 },
  { id: "data-analysis", name: "Data Analysis", nameEs: "Análisis de Datos", category: "research", aiCount: 456 },
  { id: "data-cleaning", name: "Data Cleaning", nameEs: "Limpieza de Datos", category: "research", aiCount: 178 },
  { id: "data-collection", name: "Data Collection", nameEs: "Recopilación de Datos", category: "research", aiCount: 234 },
  { id: "data-entry", name: "Data Entry", nameEs: "Entrada de Datos", category: "productivity", aiCount: 145 },
  { id: "data-extraction", name: "Data Extraction", nameEs: "Extracción de Datos", category: "research", aiCount: 267 },
  { id: "data-mining", name: "Data Mining", nameEs: "Minería de Datos", category: "research", aiCount: 189 },
  { id: "data-processing", name: "Data Processing", nameEs: "Procesamiento de Datos", category: "research", aiCount: 345 },
  { id: "data-science", name: "Data Science", nameEs: "Ciencia de Datos", category: "research", aiCount: 234 },
  { id: "data-visualization", name: "Data Visualization", nameEs: "Visualización de Datos", category: "research", aiCount: 289 },
  { id: "database-management", name: "Database Management", nameEs: "Gestión de Bases de Datos", category: "development", aiCount: 178 },
  { id: "debugging", name: "Debugging", nameEs: "Depuración", category: "development", aiCount: 234 },
  { id: "decision-making", name: "Decision Making", nameEs: "Toma de Decisiones", category: "business", aiCount: 89 },
  { id: "design-generation", name: "Design Generation", nameEs: "Generación de Diseño", category: "design", aiCount: 345 },
  { id: "diagram-creation", name: "Diagram Creation", nameEs: "Creación de Diagramas", category: "productivity", aiCount: 123 },
  { id: "dialogue-generation", name: "Dialogue Generation", nameEs: "Generación de Diálogos", category: "content", aiCount: 78 },
  { id: "dictation", name: "Dictation", nameEs: "Dictado", category: "productivity", aiCount: 156 },
  { id: "document-analysis", name: "Document Analysis", nameEs: "Análisis de Documentos", category: "productivity", aiCount: 234 },
  { id: "document-conversion", name: "Document Conversion", nameEs: "Conversión de Documentos", category: "productivity", aiCount: 145 },
  { id: "document-creation", name: "Document Creation", nameEs: "Creación de Documentos", category: "productivity", aiCount: 189 },
  { id: "document-editing", name: "Document Editing", nameEs: "Edición de Documentos", category: "productivity", aiCount: 267 },
  { id: "document-extraction", name: "Document Extraction", nameEs: "Extracción de Documentos", category: "productivity", aiCount: 178 },
  { id: "document-generation", name: "Document Generation", nameEs: "Generación de Documentos", category: "productivity", aiCount: 234 },
  { id: "document-management", name: "Document Management", nameEs: "Gestión de Documentos", category: "productivity", aiCount: 189 },
  { id: "document-organization", name: "Document Organization", nameEs: "Organización de Documentos", category: "productivity", aiCount: 123 },
  { id: "document-processing", name: "Document Processing", nameEs: "Procesamiento de Documentos", category: "productivity", aiCount: 267 },
  { id: "document-summarization", name: "Document Summarization", nameEs: "Resumen de Documentos", category: "productivity", aiCount: 345 },
  { id: "domain-name-suggestion", name: "Domain Name Suggestion", nameEs: "Sugerencia de Dominios", category: "business", aiCount: 34 },
  { id: "drawing", name: "Drawing", nameEs: "Dibujo", category: "creative", aiCount: 234 },
  { id: "duplication-detection", name: "Duplication Detection", nameEs: "Detección de Duplicados", category: "productivity", aiCount: 89 },

  // E - Tasks starting with E
  { id: "ebook-creation", name: "eBook Creation", nameEs: "Creación de eBooks", category: "content", aiCount: 156 },
  { id: "ecommerce-optimization", name: "E-commerce Optimization", nameEs: "Optimización E-commerce", category: "business", aiCount: 123 },
  { id: "editing", name: "Editing", nameEs: "Edición", category: "content", aiCount: 345 },
  { id: "education-content", name: "Education Content", nameEs: "Contenido Educativo", category: "education", aiCount: 234 },
  { id: "educational-content", name: "Educational Content", nameEs: "Contenido Educativo", category: "education", aiCount: 289 },
  { id: "email-automation", name: "Email Automation", nameEs: "Automatización de Email", category: "marketing", aiCount: 234 },
  { id: "email-composition", name: "Email Composition", nameEs: "Composición de Email", category: "communication", aiCount: 189 },
  { id: "email-generation", name: "Email Generation", nameEs: "Generación de Email", category: "communication", aiCount: 267 },
  { id: "email-marketing", name: "Email Marketing", nameEs: "Email Marketing", category: "marketing", aiCount: 289 },
  { id: "email-optimization", name: "Email Optimization", nameEs: "Optimización de Email", category: "marketing", aiCount: 178 },
  { id: "email-writing", name: "Email Writing", nameEs: "Escritura de Email", category: "communication", aiCount: 234 },
  { id: "emoji-generation", name: "Emoji Generation", nameEs: "Generación de Emojis", category: "creative", aiCount: 45 },
  { id: "employee-engagement", name: "Employee Engagement", nameEs: "Compromiso de Empleados", category: "business", aiCount: 67 },
  { id: "employee-onboarding", name: "Employee Onboarding", nameEs: "Incorporación de Empleados", category: "business", aiCount: 78 },
  { id: "employee-training", name: "Employee Training", nameEs: "Formación de Empleados", category: "education", aiCount: 145 },
  { id: "energy-optimization", name: "Energy Optimization", nameEs: "Optimización de Energía", category: "business", aiCount: 34 },
  { id: "enterprise-search", name: "Enterprise Search", nameEs: "Búsqueda Empresarial", category: "productivity", aiCount: 89 },
  { id: "error-detection", name: "Error Detection", nameEs: "Detección de Errores", category: "development", aiCount: 178 },
  { id: "essay-writing", name: "Essay Writing", nameEs: "Escritura de Ensayos", category: "content", aiCount: 234 },
  { id: "event-planning", name: "Event Planning", nameEs: "Planificación de Eventos", category: "business", aiCount: 89 },
  { id: "excel-automation", name: "Excel Automation", nameEs: "Automatización de Excel", category: "productivity", aiCount: 145 },
  { id: "exercise-generation", name: "Exercise Generation", nameEs: "Generación de Ejercicios", category: "education", aiCount: 78 },
  { id: "expense-tracking", name: "Expense Tracking", nameEs: "Seguimiento de Gastos", category: "finance", aiCount: 123 },
  { id: "explanation-generation", name: "Explanation Generation", nameEs: "Generación de Explicaciones", category: "education", aiCount: 145 },

  // F - Tasks starting with F
  { id: "face-generation", name: "Face Generation", nameEs: "Generación de Rostros", category: "design", aiCount: 178 },
  { id: "face-recognition", name: "Face Recognition", nameEs: "Reconocimiento Facial", category: "development", aiCount: 123 },
  { id: "face-swap", name: "Face Swap", nameEs: "Intercambio de Rostros", category: "creative", aiCount: 89 },
  { id: "fact-checking", name: "Fact Checking", nameEs: "Verificación de Hechos", category: "research", aiCount: 67 },
  { id: "fan-art-generation", name: "Fan Art Generation", nameEs: "Generación de Fan Art", category: "creative", aiCount: 56 },
  { id: "faq-generation", name: "FAQ Generation", nameEs: "Generación de FAQs", category: "content", aiCount: 123 },
  { id: "fashion-design", name: "Fashion Design", nameEs: "Diseño de Moda", category: "design", aiCount: 145 },
  { id: "feature-extraction", name: "Feature Extraction", nameEs: "Extracción de Características", category: "development", aiCount: 89 },
  { id: "feedback-analysis", name: "Feedback Analysis", nameEs: "Análisis de Feedback", category: "business", aiCount: 178 },
  { id: "feedback-generation", name: "Feedback Generation", nameEs: "Generación de Feedback", category: "education", aiCount: 145 },
  { id: "file-conversion", name: "File Conversion", nameEs: "Conversión de Archivos", category: "productivity", aiCount: 123 },
  { id: "file-organization", name: "File Organization", nameEs: "Organización de Archivos", category: "productivity", aiCount: 89 },
  { id: "film-editing", name: "Film Editing", nameEs: "Edición de Películas", category: "creative", aiCount: 145 },
  { id: "financial-analysis", name: "Financial Analysis", nameEs: "Análisis Financiero", category: "finance", aiCount: 234 },
  { id: "financial-planning", name: "Financial Planning", nameEs: "Planificación Financiera", category: "finance", aiCount: 178 },
  { id: "fitness-planning", name: "Fitness Planning", nameEs: "Planificación Fitness", category: "health", aiCount: 145 },
  { id: "flight-booking", name: "Flight Booking", nameEs: "Reserva de Vuelos", category: "productivity", aiCount: 56 },
  { id: "flyer-design", name: "Flyer Design", nameEs: "Diseño de Flyers", category: "design", aiCount: 123 },
  { id: "font-generation", name: "Font Generation", nameEs: "Generación de Fuentes", category: "design", aiCount: 67 },
  { id: "form-creation", name: "Form Creation", nameEs: "Creación de Formularios", category: "productivity", aiCount: 89 },
  { id: "formatting", name: "Formatting", nameEs: "Formateo", category: "productivity", aiCount: 123 },
  { id: "formula-generation", name: "Formula Generation", nameEs: "Generación de Fórmulas", category: "development", aiCount: 78 },
  { id: "fraud-detection", name: "Fraud Detection", nameEs: "Detección de Fraude", category: "finance", aiCount: 145 },
  { id: "freelance-management", name: "Freelance Management", nameEs: "Gestión Freelance", category: "business", aiCount: 67 },

  // G - Tasks starting with G
  { id: "game-asset-generation", name: "Game Asset Generation", nameEs: "Generación de Assets de Juegos", category: "creative", aiCount: 189 },
  { id: "game-design", name: "Game Design", nameEs: "Diseño de Juegos", category: "creative", aiCount: 234 },
  { id: "game-development", name: "Game Development", nameEs: "Desarrollo de Juegos", category: "development", aiCount: 289 },
  { id: "ghost-writing", name: "Ghost Writing", nameEs: "Escritura Fantasma", category: "content", aiCount: 145 },
  { id: "gif-creation", name: "GIF Creation", nameEs: "Creación de GIFs", category: "creative", aiCount: 123 },
  { id: "goal-setting", name: "Goal Setting", nameEs: "Establecimiento de Metas", category: "productivity", aiCount: 89 },
  { id: "grammar-checking", name: "Grammar Checking", nameEs: "Verificación Gramatical", category: "content", aiCount: 345 },
  { id: "graphic-design", name: "Graphic Design", nameEs: "Diseño Gráfico", category: "design", aiCount: 456 },
  { id: "greeting-card-design", name: "Greeting Card Design", nameEs: "Diseño de Tarjetas", category: "design", aiCount: 67 },
  { id: "growth-hacking", name: "Growth Hacking", nameEs: "Growth Hacking", category: "marketing", aiCount: 123 },

  // H - Tasks starting with H
  { id: "habit-tracking", name: "Habit Tracking", nameEs: "Seguimiento de Hábitos", category: "productivity", aiCount: 78 },
  { id: "hair-style-generation", name: "Hair Style Generation", nameEs: "Generación de Peinados", category: "design", aiCount: 34 },
  { id: "headline-generation", name: "Headline Generation", nameEs: "Generación de Titulares", category: "content", aiCount: 234 },
  { id: "health-monitoring", name: "Health Monitoring", nameEs: "Monitoreo de Salud", category: "health", aiCount: 189 },
  { id: "healthcare-analytics", name: "Healthcare Analytics", nameEs: "Analítica de Salud", category: "health", aiCount: 145 },
  { id: "home-design", name: "Home Design", nameEs: "Diseño de Hogar", category: "design", aiCount: 123 },
  { id: "homework-help", name: "Homework Help", nameEs: "Ayuda con Tareas", category: "education", aiCount: 234 },
  { id: "hr-automation", name: "HR Automation", nameEs: "Automatización de RRHH", category: "business", aiCount: 156 },
  { id: "human-resources", name: "Human Resources", nameEs: "Recursos Humanos", category: "business", aiCount: 189 },
  { id: "hunting-assistant", name: "Hunting Assistant", nameEs: "Asistente de Caza", category: "entertainment", aiCount: 12 },

  // I - Tasks starting with I
  { id: "idea-generation", name: "Idea Generation", nameEs: "Generación de Ideas", category: "creative", aiCount: 234 },
  { id: "identity-verification", name: "Identity Verification", nameEs: "Verificación de Identidad", category: "business", aiCount: 89 },
  { id: "image-captioning", name: "Image Captioning", nameEs: "Subtítulos de Imágenes", category: "content", aiCount: 178 },
  { id: "image-colorization", name: "Image Colorization", nameEs: "Colorización de Imágenes", category: "design", aiCount: 123 },
  { id: "image-compression", name: "Image Compression", nameEs: "Compresión de Imágenes", category: "design", aiCount: 89 },
  { id: "image-cropping", name: "Image Cropping", nameEs: "Recorte de Imágenes", category: "design", aiCount: 67 },
  { id: "image-editing", name: "Image Editing", nameEs: "Edición de Imágenes", category: "design", aiCount: 456 },
  { id: "image-enhancement", name: "Image Enhancement", nameEs: "Mejora de Imágenes", category: "design", aiCount: 345 },
  { id: "image-generation", name: "Image Generation", nameEs: "Generación de Imágenes", category: "design", aiCount: 567 },
  { id: "image-inpainting", name: "Image Inpainting", nameEs: "Relleno de Imágenes", category: "design", aiCount: 145 },
  { id: "image-recognition", name: "Image Recognition", nameEs: "Reconocimiento de Imágenes", category: "development", aiCount: 234 },
  { id: "image-restoration", name: "Image Restoration", nameEs: "Restauración de Imágenes", category: "design", aiCount: 178 },
  { id: "image-search", name: "Image Search", nameEs: "Búsqueda de Imágenes", category: "productivity", aiCount: 145 },
  { id: "image-segmentation", name: "Image Segmentation", nameEs: "Segmentación de Imágenes", category: "development", aiCount: 123 },
  { id: "image-style-transfer", name: "Image Style Transfer", nameEs: "Transferencia de Estilo", category: "design", aiCount: 189 },
  { id: "image-upscaling", name: "Image Upscaling", nameEs: "Ampliación de Imágenes", category: "design", aiCount: 267 },
  { id: "indoor-design", name: "Indoor Design", nameEs: "Diseño de Interiores", category: "design", aiCount: 145 },
  { id: "influencer-marketing", name: "Influencer Marketing", nameEs: "Marketing de Influencers", category: "marketing", aiCount: 123 },
  { id: "information-extraction", name: "Information Extraction", nameEs: "Extracción de Información", category: "research", aiCount: 178 },
  { id: "instagram-content", name: "Instagram Content", nameEs: "Contenido para Instagram", category: "marketing", aiCount: 234 },
  { id: "instruction-generation", name: "Instruction Generation", nameEs: "Generación de Instrucciones", category: "content", aiCount: 89 },
  { id: "interior-design", name: "Interior Design", nameEs: "Diseño de Interiores", category: "design", aiCount: 189 },
  { id: "inventory-management", name: "Inventory Management", nameEs: "Gestión de Inventario", category: "business", aiCount: 145 },
  { id: "investment-analysis", name: "Investment Analysis", nameEs: "Análisis de Inversiones", category: "finance", aiCount: 178 },
  { id: "invoice-generation", name: "Invoice Generation", nameEs: "Generación de Facturas", category: "business", aiCount: 123 },
  { id: "invoice-processing", name: "Invoice Processing", nameEs: "Procesamiento de Facturas", category: "business", aiCount: 156 },

  // J - Tasks starting with J
  { id: "job-description-writing", name: "Job Description Writing", nameEs: "Escritura de Descripciones de Trabajo", category: "business", aiCount: 145 },
  { id: "job-matching", name: "Job Matching", nameEs: "Coincidencia de Trabajo", category: "business", aiCount: 123 },
  { id: "job-search", name: "Job Search", nameEs: "Búsqueda de Empleo", category: "business", aiCount: 189 },
  { id: "joke-generation", name: "Joke Generation", nameEs: "Generación de Chistes", category: "entertainment", aiCount: 67 },
  { id: "journalism", name: "Journalism", nameEs: "Periodismo", category: "content", aiCount: 145 },
  { id: "json-generation", name: "JSON Generation", nameEs: "Generación de JSON", category: "development", aiCount: 89 },

  // K - Tasks starting with K
  { id: "keyword-analysis", name: "Keyword Analysis", nameEs: "Análisis de Palabras Clave", category: "marketing", aiCount: 234 },
  { id: "keyword-extraction", name: "Keyword Extraction", nameEs: "Extracción de Palabras Clave", category: "marketing", aiCount: 178 },
  { id: "keyword-research", name: "Keyword Research", nameEs: "Investigación de Palabras Clave", category: "marketing", aiCount: 289 },
  { id: "knowledge-base", name: "Knowledge Base", nameEs: "Base de Conocimiento", category: "business", aiCount: 145 },
  { id: "knowledge-extraction", name: "Knowledge Extraction", nameEs: "Extracción de Conocimiento", category: "research", aiCount: 89 },
  { id: "knowledge-management", name: "Knowledge Management", nameEs: "Gestión del Conocimiento", category: "business", aiCount: 156 },

  // L - Tasks starting with L
  { id: "landing-page-design", name: "Landing Page Design", nameEs: "Diseño de Landing Pages", category: "design", aiCount: 234 },
  { id: "landscape-design", name: "Landscape Design", nameEs: "Diseño de Paisajes", category: "design", aiCount: 67 },
  { id: "language-detection", name: "Language Detection", nameEs: "Detección de Idioma", category: "development", aiCount: 89 },
  { id: "language-learning", name: "Language Learning", nameEs: "Aprendizaje de Idiomas", category: "education", aiCount: 234 },
  { id: "language-modeling", name: "Language Modeling", nameEs: "Modelado de Lenguaje", category: "development", aiCount: 178 },
  { id: "language-translation", name: "Language Translation", nameEs: "Traducción de Idiomas", category: "communication", aiCount: 345 },
  { id: "laugh-generation", name: "Laugh Generation", nameEs: "Generación de Risas", category: "entertainment", aiCount: 12 },
  { id: "lead-generation", name: "Lead Generation", nameEs: "Generación de Leads", category: "marketing", aiCount: 289 },
  { id: "lead-scoring", name: "Lead Scoring", nameEs: "Puntuación de Leads", category: "marketing", aiCount: 145 },
  { id: "learning-content", name: "Learning Content", nameEs: "Contenido de Aprendizaje", category: "education", aiCount: 267 },
  { id: "legal-advice", name: "Legal Advice", nameEs: "Consejos Legales", category: "legal", aiCount: 89 },
  { id: "legal-document-analysis", name: "Legal Document Analysis", nameEs: "Análisis de Documentos Legales", category: "legal", aiCount: 123 },
  { id: "legal-document-generation", name: "Legal Document Generation", nameEs: "Generación de Documentos Legales", category: "legal", aiCount: 145 },
  { id: "legal-research", name: "Legal Research", nameEs: "Investigación Legal", category: "legal", aiCount: 78 },
  { id: "lesson-planning", name: "Lesson Planning", nameEs: "Planificación de Lecciones", category: "education", aiCount: 189 },
  { id: "letter-writing", name: "Letter Writing", nameEs: "Escritura de Cartas", category: "content", aiCount: 123 },
  { id: "logo-design", name: "Logo Design", nameEs: "Diseño de Logos", category: "design", aiCount: 289 },
  { id: "logo-generation", name: "Logo Generation", nameEs: "Generación de Logos", category: "design", aiCount: 234 },
  { id: "long-form-content", name: "Long-form Content", nameEs: "Contenido Largo", category: "content", aiCount: 178 },
  { id: "lyrics-generation", name: "Lyrics Generation", nameEs: "Generación de Letras", category: "creative", aiCount: 145 },

  // M - Tasks starting with M
  { id: "machine-learning", name: "Machine Learning", nameEs: "Machine Learning", category: "development", aiCount: 345 },
  { id: "macro-writing", name: "Macro Writing", nameEs: "Escritura de Macros", category: "development", aiCount: 67 },
  { id: "magazine-design", name: "Magazine Design", nameEs: "Diseño de Revistas", category: "design", aiCount: 45 },
  { id: "mail-automation", name: "Mail Automation", nameEs: "Automatización de Correo", category: "productivity", aiCount: 189 },
  { id: "market-analysis", name: "Market Analysis", nameEs: "Análisis de Mercado", category: "marketing", aiCount: 234 },
  { id: "market-research", name: "Market Research", nameEs: "Investigación de Mercado", category: "marketing", aiCount: 289 },
  { id: "marketing-automation", name: "Marketing Automation", nameEs: "Automatización de Marketing", category: "marketing", aiCount: 267 },
  { id: "marketing-content", name: "Marketing Content", nameEs: "Contenido de Marketing", category: "marketing", aiCount: 345 },
  { id: "meme-generation", name: "Meme Generation", nameEs: "Generación de Memes", category: "entertainment", aiCount: 89 },
  { id: "memo-writing", name: "Memo Writing", nameEs: "Escritura de Memos", category: "content", aiCount: 78 },
  { id: "memory-assistance", name: "Memory Assistance", nameEs: "Asistencia de Memoria", category: "productivity", aiCount: 56 },
  { id: "menu-design", name: "Menu Design", nameEs: "Diseño de Menús", category: "design", aiCount: 34 },
  { id: "message-generation", name: "Message Generation", nameEs: "Generación de Mensajes", category: "communication", aiCount: 189 },
  { id: "metadata-generation", name: "Metadata Generation", nameEs: "Generación de Metadatos", category: "marketing", aiCount: 123 },
  { id: "microsoft-excel", name: "Microsoft Excel", nameEs: "Microsoft Excel", category: "productivity", aiCount: 234 },
  { id: "mind-mapping", name: "Mind Mapping", nameEs: "Mapas Mentales", category: "productivity", aiCount: 145 },
  { id: "mobile-app-design", name: "Mobile App Design", nameEs: "Diseño de Apps Móviles", category: "design", aiCount: 289 },
  { id: "mockup-generation", name: "Mockup Generation", nameEs: "Generación de Mockups", category: "design", aiCount: 178 },
  { id: "mood-tracking", name: "Mood Tracking", nameEs: "Seguimiento del Estado de Ánimo", category: "health", aiCount: 67 },
  { id: "moodboard-creation", name: "Moodboard Creation", nameEs: "Creación de Moodboards", category: "design", aiCount: 89 },
  { id: "motionalysis", name: "Motion Analysis", nameEs: "Análisis de Movimiento", category: "development", aiCount: 78 },
  { id: "movie-recommendation", name: "Movie Recommendation", nameEs: "Recomendación de Películas", category: "entertainment", aiCount: 123 },
  { id: "music-composition", name: "Music Composition", nameEs: "Composición Musical", category: "creative", aiCount: 234 },
  { id: "music-generation", name: "Music Generation", nameEs: "Generación de Música", category: "creative", aiCount: 289 },
  { id: "music-mixing", name: "Music Mixing", nameEs: "Mezcla de Música", category: "creative", aiCount: 145 },
  { id: "music-production", name: "Music Production", nameEs: "Producción Musical", category: "creative", aiCount: 189 },
  { id: "music-recommendation", name: "Music Recommendation", nameEs: "Recomendación de Música", category: "entertainment", aiCount: 156 },
  { id: "music-remixing", name: "Music Remixing", nameEs: "Remix de Música", category: "creative", aiCount: 89 },

  // N - Tasks starting with N
  { id: "narrative-generation", name: "Narrative Generation", nameEs: "Generación de Narrativas", category: "content", aiCount: 145 },
  { id: "natural-language-processing", name: "Natural Language Processing", nameEs: "Procesamiento de Lenguaje Natural", category: "development", aiCount: 234 },
  { id: "navigation-assistant", name: "Navigation Assistant", nameEs: "Asistente de Navegación", category: "productivity", aiCount: 67 },
  { id: "negotiation-assistant", name: "Negotiation Assistant", nameEs: "Asistente de Negociación", category: "business", aiCount: 34 },
  { id: "news-aggregation", name: "News Aggregation", nameEs: "Agregación de Noticias", category: "content", aiCount: 178 },
  { id: "news-generation", name: "News Generation", nameEs: "Generación de Noticias", category: "content", aiCount: 123 },
  { id: "news-writing", name: "News Writing", nameEs: "Escritura de Noticias", category: "content", aiCount: 156 },
  { id: "newsletter-creation", name: "Newsletter Creation", nameEs: "Creación de Newsletters", category: "marketing", aiCount: 189 },
  { id: "niche-research", name: "Niche Research", nameEs: "Investigación de Nicho", category: "marketing", aiCount: 89 },
  { id: "note-taking", name: "Note Taking", nameEs: "Toma de Notas", category: "productivity", aiCount: 234 },
  { id: "novel-writing", name: "Novel Writing", nameEs: "Escritura de Novelas", category: "content", aiCount: 178 },

  // O - Tasks starting with O
  { id: "ocr", name: "OCR", nameEs: "OCR", category: "productivity", aiCount: 189 },
  { id: "online-course-creation", name: "Online Course Creation", nameEs: "Creación de Cursos Online", category: "education", aiCount: 234 },
  { id: "opportunity-detection", name: "Opportunity Detection", nameEs: "Detección de Oportunidades", category: "business", aiCount: 67 },
  { id: "optimization", name: "Optimization", nameEs: "Optimización", category: "business", aiCount: 234 },
  { id: "outreach-automation", name: "Outreach Automation", nameEs: "Automatización de Outreach", category: "marketing", aiCount: 145 },

  // P - Tasks starting with P
  { id: "paragraph-writing", name: "Paragraph Writing", nameEs: "Escritura de Párrafos", category: "content", aiCount: 178 },
  { id: "paraphrasing", name: "Paraphrasing", nameEs: "Parafraseo", category: "content", aiCount: 289 },
  { id: "pattern-recognition", name: "Pattern Recognition", nameEs: "Reconocimiento de Patrones", category: "development", aiCount: 156 },
  { id: "pdf-analysis", name: "PDF Analysis", nameEs: "Análisis de PDFs", category: "productivity", aiCount: 189 },
  { id: "pdf-conversion", name: "PDF Conversion", nameEs: "Conversión de PDFs", category: "productivity", aiCount: 145 },
  { id: "pdf-editing", name: "PDF Editing", nameEs: "Edición de PDFs", category: "productivity", aiCount: 123 },
  { id: "pdf-generation", name: "PDF Generation", nameEs: "Generación de PDFs", category: "productivity", aiCount: 178 },
  { id: "performance-analysis", name: "Performance Analysis", nameEs: "Análisis de Rendimiento", category: "business", aiCount: 189 },
  { id: "personal-assistant", name: "Personal Assistant", nameEs: "Asistente Personal", category: "productivity", aiCount: 234 },
  { id: "personalization", name: "Personalization", nameEs: "Personalización", category: "marketing", aiCount: 178 },
  { id: "pet-care", name: "Pet Care", nameEs: "Cuidado de Mascotas", category: "health", aiCount: 34 },
  { id: "phishing-detection", name: "Phishing Detection", nameEs: "Detección de Phishing", category: "business", aiCount: 89 },
  { id: "photo-editing", name: "Photo Editing", nameEs: "Edición de Fotos", category: "design", aiCount: 345 },
  { id: "photo-enhancement", name: "Photo Enhancement", nameEs: "Mejora de Fotos", category: "design", aiCount: 289 },
  { id: "photo-generation", name: "Photo Generation", nameEs: "Generación de Fotos", category: "design", aiCount: 234 },
  { id: "photo-restoration", name: "Photo Restoration", nameEs: "Restauración de Fotos", category: "design", aiCount: 145 },
  { id: "pitch-deck-creation", name: "Pitch Deck Creation", nameEs: "Creación de Pitch Decks", category: "business", aiCount: 123 },
  { id: "plagiarism-checking", name: "Plagiarism Checking", nameEs: "Verificación de Plagio", category: "content", aiCount: 178 },
  { id: "planning", name: "Planning", nameEs: "Planificación", category: "productivity", aiCount: 234 },
  { id: "playlist-generation", name: "Playlist Generation", nameEs: "Generación de Playlists", category: "entertainment", aiCount: 89 },
  { id: "plot-generation", name: "Plot Generation", nameEs: "Generación de Tramas", category: "content", aiCount: 78 },
  { id: "podcast-creation", name: "Podcast Creation", nameEs: "Creación de Podcasts", category: "content", aiCount: 189 },
  { id: "podcast-editing", name: "Podcast Editing", nameEs: "Edición de Podcasts", category: "content", aiCount: 145 },
  { id: "podcast-transcription", name: "Podcast Transcription", nameEs: "Transcripción de Podcasts", category: "content", aiCount: 123 },
  { id: "poem-generation", name: "Poem Generation", nameEs: "Generación de Poemas", category: "creative", aiCount: 145 },
  { id: "policy-writing", name: "Policy Writing", nameEs: "Escritura de Políticas", category: "legal", aiCount: 67 },
  { id: "portfolio-creation", name: "Portfolio Creation", nameEs: "Creación de Portafolios", category: "design", aiCount: 123 },
  { id: "poster-design", name: "Poster Design", nameEs: "Diseño de Pósters", category: "design", aiCount: 178 },
  { id: "powerpoint-generation", name: "PowerPoint Generation", nameEs: "Generación de PowerPoint", category: "productivity", aiCount: 189 },
  { id: "prediction", name: "Prediction", nameEs: "Predicción", category: "research", aiCount: 234 },
  { id: "presentation-design", name: "Presentation Design", nameEs: "Diseño de Presentaciones", category: "design", aiCount: 267 },
  { id: "presentation-generation", name: "Presentation Generation", nameEs: "Generación de Presentaciones", category: "productivity", aiCount: 289 },
  { id: "pricing-optimization", name: "Pricing Optimization", nameEs: "Optimización de Precios", category: "business", aiCount: 123 },
  { id: "product-description", name: "Product Description", nameEs: "Descripción de Productos", category: "marketing", aiCount: 289 },
  { id: "product-design", name: "Product Design", nameEs: "Diseño de Productos", category: "design", aiCount: 234 },
  { id: "product-development", name: "Product Development", nameEs: "Desarrollo de Productos", category: "business", aiCount: 178 },
  { id: "product-photography", name: "Product Photography", nameEs: "Fotografía de Productos", category: "design", aiCount: 145 },
  { id: "product-recommendation", name: "Product Recommendation", nameEs: "Recomendación de Productos", category: "marketing", aiCount: 189 },
  { id: "production-planning", name: "Production Planning", nameEs: "Planificación de Producción", category: "business", aiCount: 89 },
  { id: "programming", name: "Programming", nameEs: "Programación", category: "development", aiCount: 456 },
  { id: "project-management", name: "Project Management", nameEs: "Gestión de Proyectos", category: "business", aiCount: 234 },
  { id: "prompt-engineering", name: "Prompt Engineering", nameEs: "Ingeniería de Prompts", category: "development", aiCount: 178 },
  { id: "prompt-generation", name: "Prompt Generation", nameEs: "Generación de Prompts", category: "development", aiCount: 234 },
  { id: "proposal-writing", name: "Proposal Writing", nameEs: "Escritura de Propuestas", category: "business", aiCount: 145 },
  { id: "prototyping", name: "Prototyping", nameEs: "Prototipado", category: "design", aiCount: 189 },

  // Q - Tasks starting with Q
  { id: "qa-testing", name: "QA Testing", nameEs: "Testing de Calidad", category: "development", aiCount: 178 },
  { id: "qr-code-generation", name: "QR Code Generation", nameEs: "Generación de QR", category: "productivity", aiCount: 67 },
  { id: "question-answering", name: "Question Answering", nameEs: "Respuesta a Preguntas", category: "productivity", aiCount: 234 },
  { id: "question-generation", name: "Question Generation", nameEs: "Generación de Preguntas", category: "education", aiCount: 145 },
  { id: "quotation-generation", name: "Quotation Generation", nameEs: "Generación de Cotizaciones", category: "business", aiCount: 78 },

  // R - Tasks starting with R
  { id: "recipe-generation", name: "Recipe Generation", nameEs: "Generación de Recetas", category: "entertainment", aiCount: 89 },
  { id: "recommendation-engine", name: "Recommendation Engine", nameEs: "Motor de Recomendaciones", category: "marketing", aiCount: 178 },
  { id: "recruiting", name: "Recruiting", nameEs: "Reclutamiento", category: "business", aiCount: 189 },
  { id: "reddit-content", name: "Reddit Content", nameEs: "Contenido para Reddit", category: "marketing", aiCount: 67 },
  { id: "resume-building", name: "Resume Building", nameEs: "Creación de Currículums", category: "business", aiCount: 234 },
  { id: "resume-writing", name: "Resume Writing", nameEs: "Escritura de Currículums", category: "business", aiCount: 289 },
  { id: "retouching", name: "Retouching", nameEs: "Retoque", category: "design", aiCount: 178 },
  { id: "revenue-optimization", name: "Revenue Optimization", nameEs: "Optimización de Ingresos", category: "business", aiCount: 145 },
  { id: "risk-analysis", name: "Risk Analysis", nameEs: "Análisis de Riesgos", category: "finance", aiCount: 178 },
  { id: "risk-assessment", name: "Risk Assessment", nameEs: "Evaluación de Riesgos", category: "finance", aiCount: 189 },
  { id: "roadmap-planning", name: "Roadmap Planning", nameEs: "Planificación de Roadmap", category: "business", aiCount: 89 },
  { id: "robotics", name: "Robotics", nameEs: "Robótica", category: "development", aiCount: 123 },
  { id: "route-optimization", name: "Route Optimization", nameEs: "Optimización de Rutas", category: "business", aiCount: 78 },

  // S - Tasks starting with S
  { id: "sales-automation", name: "Sales Automation", nameEs: "Automatización de Ventas", category: "marketing", aiCount: 234 },
  { id: "sales-copy", name: "Sales Copy", nameEs: "Texto de Ventas", category: "marketing", aiCount: 189 },
  { id: "sales-enablement", name: "Sales Enablement", nameEs: "Habilitación de Ventas", category: "marketing", aiCount: 145 },
  { id: "sales-forecasting", name: "Sales Forecasting", nameEs: "Pronóstico de Ventas", category: "marketing", aiCount: 178 },
  { id: "scenario-generation", name: "Scenario Generation", nameEs: "Generación de Escenarios", category: "creative", aiCount: 67 },
  { id: "scheduling", name: "Scheduling", nameEs: "Programación", category: "productivity", aiCount: 189 },
  { id: "schema-generation", name: "Schema Generation", nameEs: "Generación de Esquemas", category: "development", aiCount: 89 },
  { id: "screenplay-writing", name: "Screenplay Writing", nameEs: "Escritura de Guiones", category: "content", aiCount: 123 },
  { id: "screenshot-design", name: "Screenshot Design", nameEs: "Diseño de Capturas", category: "design", aiCount: 56 },
  { id: "script-generation", name: "Script Generation", nameEs: "Generación de Scripts", category: "content", aiCount: 234 },
  { id: "script-writing", name: "Script Writing", nameEs: "Escritura de Scripts", category: "content", aiCount: 189 },
  { id: "search-engine-optimization", name: "Search Engine Optimization", nameEs: "SEO", category: "marketing", aiCount: 345 },
  { id: "security-analysis", name: "Security Analysis", nameEs: "Análisis de Seguridad", category: "development", aiCount: 178 },
  { id: "self-improvement", name: "Self Improvement", nameEs: "Auto-mejora", category: "productivity", aiCount: 123 },
  { id: "sentiment-analysis", name: "Sentiment Analysis", nameEs: "Análisis de Sentimiento", category: "research", aiCount: 234 },
  { id: "seo-optimization", name: "SEO Optimization", nameEs: "Optimización SEO", category: "marketing", aiCount: 289 },
  { id: "shader-generation", name: "Shader Generation", nameEs: "Generación de Shaders", category: "development", aiCount: 45 },
  { id: "shortcut-creation", name: "Shortcut Creation", nameEs: "Creación de Atajos", category: "productivity", aiCount: 34 },
  { id: "sleep-tracking", name: "Sleep Tracking", nameEs: "Seguimiento del Sueño", category: "health", aiCount: 78 },
  { id: "slug-generation", name: "Slug Generation", nameEs: "Generación de Slugs", category: "development", aiCount: 56 },
  { id: "smart-home", name: "Smart Home", nameEs: "Hogar Inteligente", category: "productivity", aiCount: 123 },
  { id: "sms-generation", name: "SMS Generation", nameEs: "Generación de SMS", category: "communication", aiCount: 89 },
  { id: "social-media", name: "Social Media", nameEs: "Redes Sociales", category: "marketing", aiCount: 345 },
  { id: "social-media-content", name: "Social Media Content", nameEs: "Contenido de Redes Sociales", category: "marketing", aiCount: 289 },
  { id: "social-media-management", name: "Social Media Management", nameEs: "Gestión de Redes Sociales", category: "marketing", aiCount: 234 },
  { id: "social-media-monitoring", name: "Social Media Monitoring", nameEs: "Monitoreo de Redes Sociales", category: "marketing", aiCount: 178 },
  { id: "social-media-scheduling", name: "Social Media Scheduling", nameEs: "Programación de Redes Sociales", category: "marketing", aiCount: 189 },
  { id: "song-generation", name: "Song Generation", nameEs: "Generación de Canciones", category: "creative", aiCount: 189 },
  { id: "song-writing", name: "Song Writing", nameEs: "Escritura de Canciones", category: "creative", aiCount: 145 },
  { id: "sound-design", name: "Sound Design", nameEs: "Diseño de Sonido", category: "creative", aiCount: 178 },
  { id: "sound-generation", name: "Sound Generation", nameEs: "Generación de Sonidos", category: "creative", aiCount: 145 },
  { id: "speech-recognition", name: "Speech Recognition", nameEs: "Reconocimiento de Voz", category: "development", aiCount: 234 },
  { id: "speech-synthesis", name: "Speech Synthesis", nameEs: "Síntesis de Voz", category: "creative", aiCount: 289 },
  { id: "speech-to-text", name: "Speech to Text", nameEs: "Voz a Texto", category: "productivity", aiCount: 267 },
  { id: "spell-checking", name: "Spell Checking", nameEs: "Corrección Ortográfica", category: "content", aiCount: 178 },
  { id: "spreadsheet-automation", name: "Spreadsheet Automation", nameEs: "Automatización de Hojas", category: "productivity", aiCount: 189 },
  { id: "spreadsheet-generation", name: "Spreadsheet Generation", nameEs: "Generación de Hojas", category: "productivity", aiCount: 145 },
  { id: "spreadsheet-analysis", name: "Spreadsheet Analysis", nameEs: "Análisis de Hojas", category: "productivity", aiCount: 123 },
  { id: "sql-generation", name: "SQL Generation", nameEs: "Generación de SQL", category: "development", aiCount: 178 },
  { id: "story-generation", name: "Story Generation", nameEs: "Generación de Historias", category: "content", aiCount: 234 },
  { id: "story-writing", name: "Story Writing", nameEs: "Escritura de Historias", category: "content", aiCount: 267 },
  { id: "storyboard-creation", name: "Storyboard Creation", nameEs: "Creación de Storyboards", category: "creative", aiCount: 89 },
  { id: "study-assistant", name: "Study Assistant", nameEs: "Asistente de Estudio", category: "education", aiCount: 189 },
  { id: "style-transfer", name: "Style Transfer", nameEs: "Transferencia de Estilo", category: "design", aiCount: 145 },
  { id: "subtitle-generation", name: "Subtitle Generation", nameEs: "Generación de Subtítulos", category: "content", aiCount: 234 },
  { id: "summarization", name: "Summarization", nameEs: "Resumen", category: "content", aiCount: 345 },
  { id: "supply-chain", name: "Supply Chain", nameEs: "Cadena de Suministro", category: "business", aiCount: 89 },
  { id: "survey-creation", name: "Survey Creation", nameEs: "Creación de Encuestas", category: "research", aiCount: 123 },
  { id: "svg-generation", name: "SVG Generation", nameEs: "Generación de SVG", category: "design", aiCount: 89 },
  { id: "swot-analysis", name: "SWOT Analysis", nameEs: "Análisis FODA", category: "business", aiCount: 78 },

  // T - Tasks starting with T
  { id: "tattoo-design", name: "Tattoo Design", nameEs: "Diseño de Tatuajes", category: "design", aiCount: 45 },
  { id: "tax-preparation", name: "Tax Preparation", nameEs: "Preparación de Impuestos", category: "finance", aiCount: 89 },
  { id: "teaching", name: "Teaching", nameEs: "Enseñanza", category: "education", aiCount: 178 },
  { id: "team-collaboration", name: "Team Collaboration", nameEs: "Colaboración en Equipo", category: "business", aiCount: 145 },
  { id: "technical-documentation", name: "Technical Documentation", nameEs: "Documentación Técnica", category: "development", aiCount: 189 },
  { id: "technical-writing", name: "Technical Writing", nameEs: "Escritura Técnica", category: "content", aiCount: 234 },
  { id: "template-generation", name: "Template Generation", nameEs: "Generación de Plantillas", category: "productivity", aiCount: 178 },
  { id: "template-design", name: "Template Design", nameEs: "Diseño de Plantillas", category: "design", aiCount: 145 },
  { id: "testimonial-generation", name: "Testimonial Generation", nameEs: "Generación de Testimonios", category: "marketing", aiCount: 89 },
  { id: "text-analysis", name: "Text Analysis", nameEs: "Análisis de Texto", category: "research", aiCount: 234 },
  { id: "text-classification", name: "Text Classification", nameEs: "Clasificación de Texto", category: "development", aiCount: 145 },
  { id: "text-completion", name: "Text Completion", nameEs: "Completado de Texto", category: "content", aiCount: 267 },
  { id: "text-editing", name: "Text Editing", nameEs: "Edición de Texto", category: "content", aiCount: 289 },
  { id: "text-extraction", name: "Text Extraction", nameEs: "Extracción de Texto", category: "productivity", aiCount: 178 },
  { id: "text-generation", name: "Text Generation", nameEs: "Generación de Texto", category: "content", aiCount: 456 },
  { id: "text-processing", name: "Text Processing", nameEs: "Procesamiento de Texto", category: "productivity", aiCount: 234 },
  { id: "text-summarization", name: "Text Summarization", nameEs: "Resumen de Texto", category: "content", aiCount: 345 },
  { id: "text-to-image", name: "Text to Image", nameEs: "Texto a Imagen", category: "design", aiCount: 378 },
  { id: "text-to-speech", name: "Text to Speech", nameEs: "Texto a Voz", category: "creative", aiCount: 289 },
  { id: "text-to-video", name: "Text to Video", nameEs: "Texto a Video", category: "video", aiCount: 234 },
  { id: "thumbnail-generation", name: "Thumbnail Generation", nameEs: "Generación de Miniaturas", category: "design", aiCount: 189 },
  { id: "ticket-classification", name: "Ticket Classification", nameEs: "Clasificación de Tickets", category: "business", aiCount: 78 },
  { id: "time-management", name: "Time Management", nameEs: "Gestión del Tiempo", category: "productivity", aiCount: 145 },
  { id: "time-tracking", name: "Time Tracking", nameEs: "Seguimiento del Tiempo", category: "productivity", aiCount: 123 },
  { id: "timeline-creation", name: "Timeline Creation", nameEs: "Creación de Líneas de Tiempo", category: "productivity", aiCount: 56 },
  { id: "title-generation", name: "Title Generation", nameEs: "Generación de Títulos", category: "content", aiCount: 234 },
  { id: "to-do-list", name: "To-Do List", nameEs: "Lista de Tareas", category: "productivity", aiCount: 189 },
  { id: "tool-recommendation", name: "Tool Recommendation", nameEs: "Recomendación de Herramientas", category: "productivity", aiCount: 145 },
  { id: "topic-generation", name: "Topic Generation", nameEs: "Generación de Temas", category: "content", aiCount: 178 },
  { id: "topic-research", name: "Topic Research", nameEs: "Investigación de Temas", category: "research", aiCount: 189 },
  { id: "tour-planning", name: "Tour Planning", nameEs: "Planificación de Viajes", category: "productivity", aiCount: 67 },
  { id: "trading", name: "Trading", nameEs: "Trading", category: "finance", aiCount: 178 },
  { id: "training-content", name: "Training Content", nameEs: "Contenido de Formación", category: "education", aiCount: 156 },
  { id: "transcription", name: "Transcription", nameEs: "Transcripción", category: "productivity", aiCount: 289 },
  { id: "translation", name: "Translation", nameEs: "Traducción", category: "communication", aiCount: 345 },
  { id: "travel-planning", name: "Travel Planning", nameEs: "Planificación de Viajes", category: "productivity", aiCount: 123 },
  { id: "trend-analysis", name: "Trend Analysis", nameEs: "Análisis de Tendencias", category: "research", aiCount: 189 },
  { id: "trend-detection", name: "Trend Detection", nameEs: "Detección de Tendencias", category: "research", aiCount: 145 },
  { id: "tweet-generation", name: "Tweet Generation", nameEs: "Generación de Tweets", category: "marketing", aiCount: 178 },
  { id: "typing-assistance", name: "Typing Assistance", nameEs: "Asistencia de Escritura", category: "productivity", aiCount: 123 },

  // U - Tasks starting with U
  { id: "ui-design", name: "UI Design", nameEs: "Diseño de UI", category: "design", aiCount: 289 },
  { id: "ui-generation", name: "UI Generation", nameEs: "Generación de UI", category: "design", aiCount: 234 },
  { id: "ux-design", name: "UX Design", nameEs: "Diseño de UX", category: "design", aiCount: 256 },
  { id: "ux-research", name: "UX Research", nameEs: "Investigación de UX", category: "research", aiCount: 178 },
  { id: "upselling", name: "Upselling", nameEs: "Venta Adicional", category: "marketing", aiCount: 89 },
  { id: "url-generation", name: "URL Generation", nameEs: "Generación de URLs", category: "development", aiCount: 56 },
  { id: "user-research", name: "User Research", nameEs: "Investigación de Usuarios", category: "research", aiCount: 145 },
  { id: "user-testing", name: "User Testing", nameEs: "Testing de Usuarios", category: "research", aiCount: 123 },

  // V - Tasks starting with V
  { id: "vector-generation", name: "Vector Generation", nameEs: "Generación de Vectores", category: "design", aiCount: 145 },
  { id: "vector-graphics", name: "Vector Graphics", nameEs: "Gráficos Vectoriales", category: "design", aiCount: 178 },
  { id: "video-background-removal", name: "Video Background Removal", nameEs: "Eliminación de Fondo de Video", category: "video", aiCount: 123 },
  { id: "video-captioning", name: "Video Captioning", nameEs: "Subtítulos de Video", category: "video", aiCount: 189 },
  { id: "video-clip-generation", name: "Video Clip Generation", nameEs: "Generación de Clips de Video", category: "video", aiCount: 145 },
  { id: "video-compression", name: "Video Compression", nameEs: "Compresión de Video", category: "video", aiCount: 89 },
  { id: "video-creation", name: "Video Creation", nameEs: "Creación de Video", category: "video", aiCount: 345 },
  { id: "video-editing", name: "Video Editing", nameEs: "Edición de Video", category: "video", aiCount: 289 },
  { id: "video-enhancement", name: "Video Enhancement", nameEs: "Mejora de Video", category: "video", aiCount: 178 },
  { id: "video-generation", name: "Video Generation", nameEs: "Generación de Video", category: "video", aiCount: 312 },
  { id: "video-montage", name: "Video Montage", nameEs: "Montaje de Video", category: "video", aiCount: 145 },
  { id: "video-production", name: "Video Production", nameEs: "Producción de Video", category: "video", aiCount: 234 },
  { id: "video-subtitles", name: "Video Subtitles", nameEs: "Subtítulos de Video", category: "video", aiCount: 189 },
  { id: "video-summarization", name: "Video Summarization", nameEs: "Resumen de Video", category: "video", aiCount: 78 },
  { id: "video-to-text", name: "Video to Text", nameEs: "Video a Texto", category: "video", aiCount: 123 },
  { id: "video-transcription", name: "Video Transcription", nameEs: "Transcripción de Video", category: "video", aiCount: 234 },
  { id: "video-upscaling", name: "Video Upscaling", nameEs: "Ampliación de Video", category: "video", aiCount: 145 },
  { id: "video-translation", name: "Video Translation", nameEs: "Traducción de Video", category: "video", aiCount: 178 },
  { id: "virtual-assistant", name: "Virtual Assistant", nameEs: "Asistente Virtual", category: "productivity", aiCount: 234 },
  { id: "virtual-staging", name: "Virtual Staging", nameEs: "Escenografía Virtual", category: "design", aiCount: 56 },
  { id: "visualization", name: "Visualization", nameEs: "Visualización", category: "design", aiCount: 189 },
  { id: "voice-changer", name: "Voice Changer", nameEs: "Cambiador de Voz", category: "creative", aiCount: 145 },
  { id: "voice-cloning", name: "Voice Cloning", nameEs: "Clonación de Voz", category: "creative", aiCount: 189 },
  { id: "voice-generation", name: "Voice Generation", nameEs: "Generación de Voz", category: "creative", aiCount: 234 },
  { id: "voice-over", name: "Voice Over", nameEs: "Voz en Off", category: "creative", aiCount: 178 },
  { id: "voice-recognition", name: "Voice Recognition", nameEs: "Reconocimiento de Voz", category: "development", aiCount: 145 },
  { id: "voice-synthesis", name: "Voice Synthesis", nameEs: "Síntesis de Voz", category: "creative", aiCount: 267 },

  // W - Tasks starting with W
  { id: "watermark-removal", name: "Watermark Removal", nameEs: "Eliminación de Marca de Agua", category: "design", aiCount: 89 },
  { id: "web-design", name: "Web Design", nameEs: "Diseño Web", category: "design", aiCount: 289 },
  { id: "web-development", name: "Web Development", nameEs: "Desarrollo Web", category: "development", aiCount: 345 },
  { id: "web-scraping", name: "Web Scraping", nameEs: "Web Scraping", category: "research", aiCount: 178 },
  { id: "website-builder", name: "Website Builder", nameEs: "Constructor de Sitios Web", category: "development", aiCount: 234 },
  { id: "website-generation", name: "Website Generation", nameEs: "Generación de Sitios Web", category: "development", aiCount: 189 },
  { id: "whiteboard-animation", name: "Whiteboard Animation", nameEs: "Animación de Pizarra", category: "creative", aiCount: 56 },
  { id: "wiki-generation", name: "Wiki Generation", nameEs: "Generación de Wiki", category: "content", aiCount: 67 },
  { id: "workflow-automation", name: "Workflow Automation", nameEs: "Automatización de Flujos", category: "productivity", aiCount: 234 },
  { id: "writing-assistant", name: "Writing Assistant", nameEs: "Asistente de Escritura", category: "content", aiCount: 312 },

  // X - Tasks starting with X
  { id: "xml-generation", name: "XML Generation", nameEs: "Generación de XML", category: "development", aiCount: 45 },

  // Y - Tasks starting with Y
  { id: "youtube-content", name: "YouTube Content", nameEs: "Contenido para YouTube", category: "marketing", aiCount: 234 },
  { id: "youtube-thumbnails", name: "YouTube Thumbnails", nameEs: "Miniaturas de YouTube", category: "design", aiCount: 178 },
  { id: "youtube-video-ideas", name: "YouTube Video Ideas", nameEs: "Ideas de Videos YouTube", category: "marketing", aiCount: 123 },

  // Z - Tasks starting with Z
  { id: "zapier-integration", name: "Zapier Integration", nameEs: "Integración con Zapier", category: "productivity", aiCount: 67 },
  { id: "zoning-design", name: "Zoning Design", nameEs: "Diseño de Zonificación", category: "design", aiCount: 23 },
];

// Helper function to get tasks by letter
export function getTasksByLetter(letter: string): AITask[] {
  return aiTasks.filter(task => task.name.toLowerCase().startsWith(letter.toLowerCase()));
}

// Helper function to get tasks by category
export function getTasksByCategory(category: TaskCategoryType): AITask[] {
  return aiTasks.filter(task => task.category === category);
}

// Helper function to search tasks
export function searchTasks(query: string): AITask[] {
  const lowerQuery = query.toLowerCase();
  return aiTasks.filter(task => 
    task.name.toLowerCase().includes(lowerQuery) ||
    task.nameEs.toLowerCase().includes(lowerQuery)
  );
}

// Get alphabet for navigation
export const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

// Get total count
export const totalTasksCount = aiTasks.length;
